<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ5tvx6l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ5tvx6l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ5tvx6l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ5tvx6l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ5tvx6l\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z5tvx6l',
    'container.build_id' => 'bdb2e162',
    'container.build_time' => 1676985456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ5tvx6l');
