<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFeyTYYB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFeyTYYB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFeyTYYB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFeyTYYB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFeyTYYB\App_KernelDevDebugContainer([
    'container.build_hash' => 'FeyTYYB',
    'container.build_id' => 'be640d8e',
    'container.build_time' => 1676918959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFeyTYYB');
